<?php

/**
 * @file
 * This is the module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * 
 * 
 * Implements hook_form_alter() on behalf of mid_url_proxy.module.
 * 
 * @param string $form
 * @param FormStateInterface $formState
 * @param type $formId
 */
function mid_url_proxy_form_alter(&$form,  FormStateInterface $formState, $formId) {
 
  if(in_array($formId, array('mid_url_proxy_add_form', 'mid_url_proxy_edit_form'))) {
    $form['#validate'][] = 'mid_url_proxy_validate';
  }
  
}

/**
 * 
 * @param type $form
 * @param FormStateInterface $formState
 */
function mid_url_proxy_validate($form, FormStateInterface $formState){
  $formData = $formState->getUserInput();
  
  if(empty($formData['proxy_url_key'][0]['value'])) {
    $formData['proxy_url_key'][0]['value'] = NULL;
  }
  if(empty($formData['proxy_url_key'][0])) {
    $formData['proxy_url_key'][0] = NULL;
  }
  if(empty($formData['proxy_url_key'])) {
    $formData['proxy_url_key'] = NULL;
  }

  $proxyUrlKey = $formData['proxy_url_key'][0]['value'];
  
  if(!preg_match('/^[a-zA-Z0-9_-]*$/', $proxyUrlKey)) {
    $formState->setErrorByName('proxy_url_key', t("No special characters allowed"));
  }
  
}